/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThreadDemo */

#ifndef _Included_ThreadDemo
#define _Included_ThreadDemo
#ifdef __cplusplus
extern "C" {
#endif
#undef ThreadDemo_MIN_PRIORITY
#define ThreadDemo_MIN_PRIORITY 1L
#undef ThreadDemo_NORM_PRIORITY
#define ThreadDemo_NORM_PRIORITY 5L
#undef ThreadDemo_MAX_PRIORITY
#define ThreadDemo_MAX_PRIORITY 10L
/*
 * Class:     ThreadDemo
 * Method:    PrintPID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ThreadDemo_PrintPID
  (JNIEnv *, jobject, jint);

/*
 * Class:     ThreadDemo
 * Method:    GetTID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ThreadDemo_GetTID
  (JNIEnv *, jobject);

/*
 * Class:     ThreadDemo
 * Method:    GetTID_1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ThreadDemo_GetTID_11
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
