/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ThreadDemoChange */

#ifndef _Included_ThreadDemoChange
#define _Included_ThreadDemoChange
#ifdef __cplusplus
extern "C" {
#endif
#undef ThreadDemoChange_MIN_PRIORITY
#define ThreadDemoChange_MIN_PRIORITY 1L
#undef ThreadDemoChange_NORM_PRIORITY
#define ThreadDemoChange_NORM_PRIORITY 5L
#undef ThreadDemoChange_MAX_PRIORITY
#define ThreadDemoChange_MAX_PRIORITY 10L
/*
 * Class:     ThreadDemoChange
 * Method:    PrintPID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ThreadDemoChange_PrintPID
  (JNIEnv *, jobject, jint);

/*
 * Class:     ThreadDemoChange
 * Method:    GetTID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ThreadDemoChange_GetTID
  (JNIEnv *, jobject);

/*
 * Class:     ThreadDemoChange
 * Method:    ChangePrio2
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ThreadDemoChange_ChangePrio2
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
